### PR TITLE
CHECK include directories only added in case it has been found

### PR DESCRIPTION
**Pull request by rpoisel**
Executing `include_directories()` with `CHECK_INCLUDE_DIRS` being set to `NOTFOUND` leads to an error. Therefore, an additional condition has been introduced.

### CODE REVIEW

**Comment by rpoisel** [comment]
Furthermore, I'd like to encourage you to prefer using `target_include_directories()` over `include_directories()` - see https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#transitive-usage-requirements for details. Or here: https://rix0r.nl/blog/2015/08/13/cmake-guide/

**Comment by paroga** [comment]
Added via bca88b1a64816c7d02dbd5ba48283c93c983cbd3.
Ad `target_include_directories()`: I made the change already local, but it requires at least CMake 2.8.11 but Ubuntu 12.04 ships with 2.8.7. :-(

**Comment by rpoisel** [comment]
Would it be possible to merge this pull request? It does not use `target_include_directories()` and I cannot cross compile your library due to unsatisfied dependencies now. :-(

**Comment by paroga** [comment]
Did you see commit bca88b1, which is in master already?

**Comment by rpoisel** [comment]
Now I saw it. Sorry and thx! :-)

**Pull request closed without merging**
